esphome:
  name: bee-better
  friendly_name: Better BeeHyve

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

# Over-the-Air updates (platform now required)
ota:
  platform: esphome

wifi:
  ssid: "Stack52-5G"
  password: "ReallyFastStack"

#   manual_ip:
#     static_ip: 192.168.0.212
#     gateway: 192.168.0.1
#     subnet: 255.255.255.0

  ap:
    ssid: "bee-better Fallback Hotspot"
    password: "fallback123"

captive_portal:

output:
  - platform: gpio
    pin: D2
    id: led1
  - platform: gpio
    pin: D1
    id: led2

light:
  - platform: binary
    name: "LED 1"
    output: led1
  - platform: binary
    name: "LED 2"
    output: led2
